- name: Update repositories cache and install "keepalived" package
  ansible.builtin.dnf:
    name: keepalived
    state: latest
    update_cache: yes

- name: Install keepalived template
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify:
  - restart keepalived

- name: Make sure keepalived is set to start and is running
  service: state=started enabled=true name=keepalived
